### ISSUE TITLE
in file auto_mesh.cfg version should be 0.1

### ISSUE THREAD

**Issue by stephbellemare** [strayr/strayr-k-macros#4]
Macro LOAD_MESH_TEMP is calling version check on variable setup_version.
macro should be v0.1 same as setup_version in save_variables.cfg to ensure macro loads well.

or a separate macro should be created in save_variables.cfg to save the specific version of auto_mesh.cfg
///// EDIT _ ADD BELOW

actually after checking it's the whole variable section missing as LOAD_MESH_TEMP seems to be calling setup_mesh_lifespan  which seems to be missing.

**Comment by strayr** [comment]
Noted, I think I've gone to 0.2 there so I need to check what's gone on.

**Comment by strayr** [comment]
I think this has been fixed
