### ISSUE TITLE
Please Post your [TMC2209 stepper_z] section along with your other [sections] from your printer.cfg file

### ISSUE THREAD

**Issue by GadgetAngel** [strayr/strayr-k-macros#5]
All I see here are your macros but I want to see if you are using stealthChop mode or spreadCycle mode on the TMC chips and I need to see your printer.cfg file to see this type of information.

I tried to use your Mechanical gantry level macro and ended up scratching out my Z Axis couplers, but this was not the fault of the macro but I do need to figure out if you are using stealtchop mode or spreadcycle mode on the Z Axis:
![image](https://user-images.githubusercontent.com/33468777/172057801-3cb6374d-b820-4020-a209-73b47ea65d89.png)

**Comment by strayr** [comment]
ooof, no, that went really wrong. I'm so sorry. I did warn that it was potentially dangerous. 

 I'll get cleaned up example config with explanatory notes posted today. 
I was using solid couplers on my ender3 frame and am using spring couplers in compression with an 8mm bearing ball between the lead screw and stepper in my prusa framed printer.

**Comment by GadgetAngel** [comment]
So will this always happen if I use spring couplers?  Will the macro not detect a stall on the Z Axis if my 3D printer uses spring Couplers?  Can you provide a URL for couplers that you recommend?

**Comment by strayr** [comment]
It's not using stall detection, it's reducing current and ramming the z
against the endstops forcing skipped steps.

**Comment by strayr** [comment]
https://github.com/strayr/sample_klipper_configs/tree/main/MK2-Bear has my setup for a Z with independent stepper drivers

I'm sorry for the delay in dealing with this.
